### ISSUE TITLE
examples fail: cannot import name 'eigenspectrum' from 'openfermion.utils'

### ISSUE THREAD

**Issue by yurivict** [bsenjean/Openfermion-Dirac#6]
```
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-OpenFermion-Dirac/work-py39/Openfermion-Dirac-cc08a66/examples/H4.py", line 3, in <module>
    from openfermion.utils import eigenspectrum
ImportError: cannot import name 'eigenspectrum' from 'openfermion.utils' (/usr/local/lib/python3.9/site-packages/openfermion/utils/__init__.py)
```

OpenFermion-1.5.1
Python-3.9
FreeBSD 13.1

**Comment by ncrubin** [comment]
likely these DIRAC examples need to be updated such that the `eigenspectrum` function is imported from openfermion.linalg instead of utils.  (https://github.com/quantumlib/OpenFermion/blob/8e5e68519472172b5791343551a144f91b66dc99/src/openfermion/linalg/__init__.py#L55)

**Comment by bsenjean** [comment]
This is now fixed, thank you for noticing !
